name: EnderShortcut
description: Adds a balanced /ec command.
version: "${project.version}"
api-version: 1.20
author: MSWS
main: xyz.msws.endershortcut.EnderShortcut
commands:
  enderchest:
    description: Opens your enderchest
    usage: /<command>
    permission: endershortcut.enderchest
    aliases:
      - ec
      - echest